name: Run E2E tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: pnpm run build

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: build

      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          APP_URL: 'http://localhost:3000'
          NEXT_PUBLIC_API_BASE_URL: 'https://ignite-devstore-api-beige.vercel.app/'
        with:
          start: pnpm start
          browser: chrome
